#$RNFirebaseAsStaticFramework = true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ocon' do
  config = use_native_modules!
  #use_frameworks!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
 


  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'

  pod 'react-native-create-thumbnail', :path => '../node_modules/react-native-create-thumbnail'

  target 'oconTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  

  post_install do |installer|
    react_native_post_install(installer)
   " __apply_Xcode_12_5_M1_post_install_workaround(installer)"
  end
end
